version: '3.7'
services:
  database:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment: 
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
volumes:
  database: